# Generated by Django 3.1.4 on 2021-02-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsnake', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='difficulty',
            field=models.CharField(default='', max_length=1),
        ),
    ]
